name: PlayerInvisibilityFlag-WG
version: 1.0-b4
author: Space995
depend: [WorldGuard]

description: Adds the player-invisbility WorldGuard flag. Works with WorldGuard 6.2+.
main: io.github.space995.player_invisibility_flag.PlayerInvisibilityFlag_Plugin
